from django.contrib import admin
from wc.models import *


class SimulationAdmin(admin.ModelAdmin):
    fieldset = [
            (None, {'fields': ['name', 'user', 'batch', 'ip', 'length', 
                               'replicate_index', 'wcmodel',  'description']}),
            ('Autogenerated', {'fields': ['OptionValue', 'ParameterValue']})]

admin.site.register(WCModel)
admin.site.register(Simulation, SimulationAdmin)
admin.site.register(StateProperty)
admin.site.register(Process)
admin.site.register(Parameter)
admin.site.register(Option)
admin.site.register(UserProfile)
admin.site.register(ParameterValue)
