import os
from setuptools import setup

README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()

os.chdir(os.path.normpath(os.path.join(os.path.abspath(__file__), os.pardir))

setup(
    name='django-wcdb',
    version='1.0.1',
    packages=['wcdb'],
    include_package_data=True,
    license='FreeBSD',
    description='A Django app for managing data generated by WholeCell Models.',
    long_description=README,
    url='https://www.github.com/CovertLab/WholeCellDB',
    author='Nolan Phillips',
    author_email='ncphillips@upei.ca',
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
      # 'License :: OSI Approved :: BSD License :: FreeBSD', 
        'Natural Language :: English',
      # 'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Scientific/Engineering',
        'Topic :: Scientific/Engineering :: Bio-Informatics',
        'Topic :: Scientific/Engineering :: Information Analysis',
      # 'Topic :: Scientific/Engineering :: Visualization',
    ],
)


